#!/bin/bash
function cp_and_start_test {
	rm ../../bin/libchatcheck.so
	rm ../../bin/mmseg_stat
	rm ../../log/*
	cp libchatcheck.so ../../bin/	
	cp mmseg_stat ../../bin/	
	if [ "$1"  == "startup" ]; then
		../../bin/startup.sh
	fi

}
touch  ./version.cpp

[ -d  ./build  ] ||  mkdir ./build
cd build
cmake ../  

if  [ "$?" != "0" ]   ;then
    rm -rf ../build
else
    make -j 4

	if [ "$1" == "1" ]; then
		cp_and_start_test  startup 
	fi
fi


