#! /bin/bash
if [ $# -ne 3 ] 
then
    exit 1 
fi

process_mempool_free=`snmpget -t$1 -v2c -c $2 $3 .1.3.6.1.4.1.9.9.48.1.1.1.6.1 | cut -d ' ' -f 4`
io_mempool_free=`snmpget -t$1 -v2c -c $2 $3 .1.3.6.1.4.1.9.9.48.1.1.1.6.2 | cut -d ' ' -f 4`
driver_mempool_free=`snmpget -t$1 -v2c -c $2 $3 .1.3.6.1.4.1.9.9.48.1.1.1.6.16 | cut -d ' ' -f 4`
echo $(($process_mempool_free+$io_mempool_free+$driver_mempool_free))
