// db权限的定义
DB_MGR_DB_PRIV(Select)
DB_MGR_DB_PRIV(Insert)
DB_MGR_DB_PRIV(Update)
DB_MGR_DB_PRIV(Delete)
DB_MGR_DB_PRIV(Create)
DB_MGR_DB_PRIV(Drop)
// 屏蔽grant权限
// DB_MGR_DB_PRIV(Grant)
DB_MGR_DB_PRIV(References)
DB_MGR_DB_PRIV(Index)
DB_MGR_DB_PRIV(Alter)
DB_MGR_DB_PRIV(Create temporary tables)
DB_MGR_DB_PRIV(Lock tables)
DB_MGR_DB_PRIV(Create view)
DB_MGR_DB_PRIV(Show view)
DB_MGR_DB_PRIV(Create routine)
DB_MGR_DB_PRIV(Alter routine)
DB_MGR_DB_PRIV(Execute)
