#!/bin/sh
#应该只发送一个文件
if [ "$1" = "" ]; then
	echo  "no file  to send "
	exit
fi
#config begin
logserverip="192.168.0.3"
logserverusername=tmplog
#config end  

#get ip addr
localip=`/sbin/ifconfig eth0 | awk '$1=="inet"{print $2}' | awk -F: '{print $2}'`
if [ "$localip" = "" ]; then
	localip=`/sbin/ifconfig eth1 | awk '$1=="inet"{print $2}' | awk -F: '{print $2}'`
fi
if [ "$localip" = "" ]; then
	echo "get local ip err"
	exit
fi

savedir=/home/$logserverusername/serverlog/log
sendfile=$1

#get filesize
sendfilesize=`ls -all $sendfile | awk '{print $5 }'`
bakdir=~/protolog/bak
scp -2 -P 56000  $sendfile $logserverusername@$logserverip:$savedir/$localip-`basename $sendfile`-$sendfilesize 
if [ $? -eq 0 ]; then
		mv $sendfile $bakdir
else 
		echo "send file err : scp $sendfile $logserverusername@$logserverip:\
			$savedir/$localip-`basename $sendfile`-$sendfilesize  "
fi
