#!/bin/bash
function cp_and_start_test {
	rm ../../bin/libdirty.so
	rm ../../log/*
	cp libdirty.so ../../bin/	
	if [ "$1"  == "startup" ]; then
		../../bin/startup.sh
	fi

}

[ -d  ./build  ] ||  mkdir ./build
cd build
cmake ../  

if  [ "$?" != "0" ]   ;then
    rm -rf ../build
else
    make -j 4

	if [ "$1" == "1" ]; then
		cp_and_start_test  startup 
	fi
fi


