#!/bin/bash
while read var1 var2 var3; 
do
echo var1=${var1} var2=${var2} var3=${var3} 

tbid=$((var2%100))
dbid=$(((var2/100)%100))
if [ $dbid -lt 10 ];then
	dbid="0$dbid"
else
	dbid="$dbid"
fi
if [ $tbid -lt 10 ];then
	tbid="0$tbid"
else
	tbid="$tbid"
fi

echo ${dbid}
echo ${tbid}
mysql -u root -pta0mee <<- EOF
update sns_user_$dbid.user_photo_$tbid set album_id=${var3} where album_id=${var1} and uid=${var2};
EOF
echo "update sns_user_$dbid.user_photo_$tbid set album_id=${var3} where album_id=${var1} and uid=${var2};"
done 
exit 0
