#!/bin/bash
while read var1 var2 var3 var4 var5 var6 var7 var8; 
do
#echo var1=${var1} var2=${var2} var3=${var3} var4=$var4 var5=$var5
llocode=$var5
photo_id=$var1
tbid=$((var2%100))
dbid=$(((var2/100)%100))
if [ $dbid -lt 10 ];then
	dbid="0$dbid"
else
	dbid="$dbid"
fi
if [ $tbid -lt 10 ];then
	tbid="0$tbid"
else
	tbid="$tbid"
fi

#echo ${dbid}
#echo ${tbid}
mysql -uroot -pta0mee <<- EOF
update sns_user_$dbid.user_photo_$tbid set lloccode="${llocode}" where photo_id=$photo_id;
EOF
echo "update sns_user_$dbid.user_photo_$tbid set lloccode="${llocode}" where photo_id=$photo_id;"
done 
exit 0
