#!/bin/bash
while read var1 var2 var3 var4 var5 var6; 
do
#echo var1=${var1} var2=${var2} var3=${var3} var4=${var4}

photo_id=$var1
uid=$var2
album_id=$var3
album_key=$var4
file_name=$var5
upload_time=$var6


FILE_PATH="/opt/${file_name}"
#echo $FILE_PATH
type=`echo ${file_name} | awk -F"." '{print $2}'`
#echo $type
THUMB1_NAME=`echo ${file_name} | awk -F"." '{print $1}'`"_h.${type}"
THUMB2_NAME=`echo ${file_name} | awk -F"." '{print $1}'`"_m.${type}"
THUMB1_PATH="/opt/${THUMB1_NAME}"
THUMB2_PATH="/opt/${THUMB2_NAME}"
#echo $THUMB1_PATH
#echo $THUMB2_PATH

if [ $var1 = "photo_id" ]
then
	echo "album_id        uid     file_name       upload_time"
	sleep 1
else
#	cmd="curl -v -H 'Expect:' -F 'file=@${FILE_PATH};type=image/${type}' -F 'userid=${var2}' -F 'key=${var1}' -F 'upload_time=${var4}' 'http://192.168.9.92/cgi_upload.cgi'"
#	echo $cmd
	
	curl -H 'Expect:' -F 'file=@'${FILE_PATH}';type=image/'${type}'' -F 'photo_id='${photo_id}'' -F 'bus_path='${FILE_PATH}'' -F 'thumb1=@'${THUMB1_PATH}';type=image/'${type}'' -F 'thumb2=@'${THUMB2_PATH}';type=image/'${type}'' -F 'userid='${uid}'' -F 'key='${album_key}'' -F 'upload_time='${upload_time}'' 'http://10.1.1.58/cgi_mv_logo.cgi'



fi
done 
exit 0
