#!/bin/bash
while read var1 var2 var3 var4 var5 var6; 
do
#echo var1=${var1} var2=${var2} var3=${var3} var4=${var4}
photo_id=$var1
uid=$var2
album_id=$var3 
album_key=$var4 
file_name=$var5 
upload_time=$var6
FILE_PATH="/opt/${file_name}"
#echo ${FILE_PATH}
type=`echo ${FILE_PATH} | awk -F"." '{print $2}'`
#echo $type

if [ ! -f "$FILE_PATH" ];then
	echo "[file not find]line:$1 path: $FILE_PATH"
	exit 0
fi
if [ $upload_time = 0 ]
then
	echo "line:$1 uploadtime=0 photo_id=$var1 uid=$var2 album_key=$var4"
	exit 0
fi


if [ $var1 != "photo_id" ]
then
#	cmd="curl -v -H 'Expect:' -F 'file=@${FILE_PATH};type=image/${type}' -F 'userid=${var2}' -F 'key=${var1}' -F 'upload_time=${var4}' 'http://192.168.9.92/cgi_upload.cgi'"
#	echo $cmd
	
	curl --connect-timeout 200 -H 'Expect:' -F 'file=@'${FILE_PATH}';type=image/'${type}'' -F 'photo_id='${photo_id}'' -F 'userid='${uid}'' -F 'key='${album_key}'' -F 'upload_time='${upload_time}'' -F 'bus_path='${FILE_PATH}'' 'http://192.168.9.92/cgi_mv_pic.cgi' 

	ret=$?
	if [ $ret != 0 ]
	then
		echo "line:$1 ret:$ret"
	fi
fi
done 
exit 0
