#ifndef ONLINE_DBPROXY_H_
#define ONLINE_DBPROXY_H_

#include "sprite.h"
#include "item.h"

#define SVR_PROTO_IS_SET_PAY_PASSWD					0x008D
#define SVR_PROTO_CHK_UID							0x1005
#define SVR_PROTO_GET_USER_FLAG						0x1015
#define SVR_PROTO_SET_USER_NICK						0x114A
#define SVR_PROTO_SET_USER_FLAG						0x1146
#define SVR_PROTO_SET_VIP_LEVEL						0x11E7

#define	SVR_PROTO_SET_STAMP_IP						0x1110
#define	SVR_PROTO_SET_TASK							0x1107

#define SVR_PROTO_SET_ITEM_MAX_LIMIT				0x1130
#define	SVR_PROTO_GET_SPRITE						0x1031
#define	SVR_PROTO_SET_COLOR							0x1132
#define	SVR_PROTO_SET_ITEM							0x1136
#define	SVR_PROTO_CHARGE							0x1139
#define	SVR_PROTO_GET_ITEM							0x1018
#define	SVR_PROTO_CHK_ITEM							0x101E

#define	SVR_PROTO_ADD_FRIEND						0x1111
#define	SVR_PROTO_DEL_FRIEND						0x1112
#define	SVR_PROTO_GET_FRIEND						0x1013
#define	SVR_PROTO_DEL_MUL_FRIENDS					0x33AC

#define	SVR_PROTO_USER_CHECKIN_BLACK				0x100C

#define	SVR_PROTO_BUY_ITEM							0x1116
#define	SVR_PROTO_SELL_ITEM							0x1117

#define SVR_PROTO_CHG_HOME_ITEM						0x1147
#define	SVR_PROTO_ADD_HOME_I						0x111A
#define	SVR_PROTO_SET_HOME_I						0x111B
#define	SVR_PROTO_DEL_HOME_I						0x111C
#define	SVR_PROTO_GET_HOME_I						0x101D
#define SVR_PROTO_SET_HOME_ITM2						0x113A
#define	SVR_PROTO_RESET_HOME_I						0x11A3

#define	SVR_PROTO_ADD_BKLIST						0x11B1
#define	SVR_PROTO_DEL_BKLIST						0x11B2
#define	SVR_PROTO_GET_BKLIST						0x10B3
#define	SVR_PROTO_ADD_MAIL							0x112A
#define	SVR_PROTO_GET_MAIL							0x1033
#define	SVR_PROTO_EXCHG_ITEM						0x114D
#define	SVR_PROTO_EXCHG_GIFT						0x114F
#define SVR_SET_GIFT_LIST							0xB550

#define SVR_PROTO_FORBID_USER_24					0x115C
#define SVR_PROTO_SET_PET_SICKTYPE					0x115F

#define	SVR_PROTO_BUY_PET_ITEM						0x1165
#define	SVR_PROTO_GET_PET_ITEM_LIST					0x1066
#define	SVR_PROTO_SET_PET_ITEM						0x1167
#define	SVR_PROTO_GET_PET_WEARED					0x1068

#define SVR_PROTO_GET_PROFESSION					0x105D
#define SVR_PROTO_SET_PROFESSION					0x115E

#define SVR_PROTO_GET_TASK_TMP_INFO					0x1084
#define SVR_PROTO_SET_TASK_TMP_INFO					0x1185

#define SVR_PROTO_GET_TASK_INFO						0x10BB
#define SVR_PROTO_SET_TASK_INFO						0x11B9
#define SVR_PROTO_DEL_TASK_INFO						0x11BA

#define SVR_PROTO_GET_DEPOSIT_INFO					0x1091
#define SVR_PROTO_DEPOSIT_BEAN 						0x1190
#define SVR_PROTO_DRAW_BEAN 						0x1192

#define SVR_PROTO_PUT_ON_CLOTHES					0x113F
#define	SVR_PROTO_JAIL_USER							0x9101
#define	SVR_PROTO_POST_MSG							0x9102
#define	SVR_PROTO_ADD_BOARD							0x7101
#define	SVR_PROTO_GET_BOARD							0x7002
#define	SVR_PROTO_FIND_BOARD						0x7003
#define	SVR_PROTO_GET_PASSED_BOARD_MSG				0x7008

#define SVR_PROTO_BOARD_FLOWER						0x7105
// For Mole Messenger
#define SVR_PROTO_MOLE_MSNGER_ADD_INVITEE			0x1160
#define SVR_PROTO_GET_MOLE_MSNGER_INFO				0x1062

// For VIP
#define SVR_PROTO_CHK_VIP_INFO						0x2004

//For home information, about hot, flower, mud,v	isitor, and neighbor
#define SVR_PROTO_GET_HOT							0xB401
#define SVR_PROTO_LIST_TOP_HOT						0xB402
#define SVR_PROTO_VOTE_HOME							0xB503
#define SVR_PROTO_ADD_HOT							0xB506
#define SVR_PROTO_LIST_RECENT_VISITOR				0xB405
#define SVR_PROTO_ADD_NEIGHBOR						0xB506
#define SVR_PROTO_LIST_NEIGHBOR						0xB407
#define SVR_PROTO_CLEAN_MUD							0xB509
#define SVR_PROTO_CLEAN_ONE_MUD						0xB511
#define SVR_PROTO_LEAVE_HOME_MSG					0xC511
#define SVR_PROTO_VERIFY_HOME_MSG					0xC512
#define SVR_PROTO_REPLY_HOME_MSG					0xC516
#define SVR_PROTO_GET_MM_TREE_INFO					0x4401
#define SVR_PROTO_OPERATE_HOME_TYPE_OBJ				0x4502
#define SVR_PROTO_LIST_OPERATED						0x4403
#define SVR_PROTO_PICK_MM_TREE_FRUIT				0x4504
#define SVR_PROTO_GET_HOME_TYPE_LIST				0x4405
#define SVR_PROTO_GET_INFO_BY_TYPE					0x4408

#define SVR_PROTO_GET_HOME_MSG						0xC414
#define SVR_PROTO_DEL_HOME_MSG						0xC515

//for birthday airship
#define SVR_PROTO_SET_BIRTHDAY						0x1180
#define SVR_PROTO_ISSET_BIRTHDAY					0x1081

// Memory DB
#define SVR_PROTO_CHK_IF_STH_DONE					0xC002
#define SVR_PROTO_SET_STH_DONE						0xC101
#define SVR_PROTO_CLEAN_STH_DONE					0xC105
#define SVR_PROTO_SET_DAY_COUNT						0xC107

#define SVR_PROTO_GET_EGG_HATCH_TIMES				0xB465
#define SVR_PROTO_SET_EGG_HATCH_TIMES				0xB566
#define SVR_PROTO_BUY_SOME_ITEMS					0x11E4
#define SVR_PROTO_ADD_LAMU_GROWTH					0x11E9

#define SVR_PROTO_RAND_TIMES						0xB468
#define SVR_PROTO_RAND_ITEM_WANT					0xB567
#define SVR_PROTO_GET_PET_ATTIRE_CNT				0x10E8
#define SVR_PROTO_GET_ITEMS_CNT_IN_BAG				0x1096
#define SVR_PROTO_GET_QUES_NAIRE_INFO				0xC014

#define SVR_PROTO_GET_MONTH_TASKS					0xC030
#define SVR_PROTO_SET_MONTH_TASK					0xC131

//For ask and answer question system
#define SVR_PROTO_SET_ASK_ANSWER_INFO				0xB530
#define SVR_PROTO_GET_ASK_ANSWER_INFO				0xB431
//
#define SVR_PROTO_GET_COUNT							0xC011
#define SVR_PROTO_SET_COUNT							0xC112
#define SVR_PROTO_GET_CNT_LIST						0xC013

#define SVR_PROTO_GET_DAY_LIMIT_LIST				0xC00C

#define SVR_PROTO_SET_QUESTIONNAIRE					0xC120

// Temperarily Use Only
#define SVR_PROTO_SUBMIT_PERSONAL_INFO				0x0141
#define SVR_PROTO_CHK_IF_INFO_SUBMITTED				0x0042

#define SVR_PROTO_CHATLOG							0xF133
#define SVR_PROTO_ADD_CHANGE_LOG					0xF103
#define SVR_PROTO_ADD_LOGIN_EXIT_INFO				0xF105

// For Mole Party
#define SVR_PROTO_GET_PARTY_COUNT					0x6404
#define SVR_PROTO_GET_MOLE_PARTY					0x6402
#define SVR_PROTO_SET_MOLE_PARTY					0x6501
#define SVR_PROTO_GET_OWN_MOLE_PARTY				0x6403

//For small requirement
#define SVR_PROTO_GET_QUES_ANSWER					0x7021
#define SVR_PROTO_GET_QUES_NUM						0x7024
#define SVR_PROTO_INC_RUN_TIMES						0x1182
#define SVR_PROTO_GET_RUN_TIMES						0x1083

//For home land
#define SVR_PROTO_GET_HOMELAND_ITEM					0x1021
#define SVR_PROTO_SET_HOMELAND_ITEM					0x1123
#define SVR_PROTO_HOMELAND_PLANT					0x1125
#define SVR_PROTO_ROOT_OUT_PLANT					0x1126
#define SVR_PROTO_WATER_PLANT						0x1127
#define SVR_PROTO_KILL_BUG							0x1128
#define SVR_PROTO_GET_ONE_PLANT						0x1029
#define SVR_PROTO_GET_HOMELAND_BOX_ITEM				0X102D
#define SVR_PROTO_HARVEST_FRUITS					0x112C
#define SVR_PROTO_ADD_JY_VISITOR					0X11A1
#define SVR_PROTO_LIST_RECENT_JY_VISITOR 			0X10A0
#define SVR_PROTO_SET_JY_USED_ITM 					0x113B
#define SVR_PROTO_CHK_IF_USER_EXIST					0x100A
#define SVR_PROTO_THIEF_FRUIT						0x112E
#define SVR_PROTO_DEC_POLLINATE_CNT					0x313C
#define SVR_PROTO_POLLINATE_FLOWER					0x312F
#define SVR_PROTO_EXCHANGE_ALL_TO_ANOTHER			0x3158
#define SVR_PROTO_FERTILIZE_FLOWER					0x11E2
#define SVR_PROTO_GET_FRUIT_FROM_NBR				0x10E3

#define SVR_PROTO_ADD_USER_TO_BAOHE					0xB540
#define SVR_PROTO_GET_BAOHE_OP_LIST					0xB441

#define SVR_PROTO_GET_JY_FIRE_VALUE					0xB43A
#define SVR_PROTO_DEC_JY_FIRE_VALUE					0xB539
#define SVR_PROTO_SET_JY_FIRE_STATE					0xB538
#define SVR_PROTO_ADD_JY_OP							0x114E
#define SVR_PROTO_GET_LAMU_ONE_STAT_TASK			0x10EC
#define SVR_PROTO_GET_BUILD_TEMPLE					0x10ED

#define SVR_PROTO_GET_JY_ANIMAL_ITEMS				0X3046


//mole class
#define SVR_PROTO_CREATE_CLASS						0x11F0
#define SVR_PROTO_GET_CLASS_INFO					0x10F1
#define SVR_PROTO_GET_CLASS_SIMP_INFO				0x10FC
#define SVR_PROTO_SET_CLASS_INFO					0x11F2
#define SVR_PROTO_ADD_CLASS_MEMBER					0x11F3
#define SVR_PROTO_DEL_CLASS_MEMBER					0x11F4
#define SVR_PROTO_CLASS_ADD_ITEM					0x11F5
#define SVR_PROTO_GET_CLASS_LOGO_INFO				0x10F6
#define SVR_PROTO_SET_CLASS_ITEM					0x11F7
#define SVR_PROTO_JOIN_CLASS						0x116C
#define SVR_PROTO_QUIT_CLASS						0x116D
#define SVR_PROTO_GET_FIRST_CLASS					0x10FD
#define SVR_PROTO_SET_FIRST_CLASS					0x116E
#define SVR_PROTO_DEL_CLASS							0x11F8
#define SVR_PROTO_SET_VISIT_FLAG					0x11F9
#define SVR_PROTO_GET_CLASS_ITM_UNUSED				0x10FA
#define SVR_PROTO_DELETE_CLASS_ITM_UNUSED			0x11FB
#define SVR_PROTO_GET_CLASS_MEMBER_LIST				0x10FE
#define SVR_PROTO_CLASS_LIST						0x106F
#define SVR_PROTO_GET_CLASS_HONOR					0x10FF
#define SVR_PROTO_GET_CLASS_QUES_REWARD				0x11A2

#define SVR_PROTO_LEAVE_CLASS_MSG					0x119A
#define SVR_PROTO_VERIFY_CLASS_MSG					0x119B
#define SVR_PROTO_GET_CLASS_MSG						0x109C
#define SVR_PROTO_DEL_CLASS_MSG						0x119D
#define SVR_PROTO_REPLY_CLASS_MSG					0x119E

#define SVR_PROTO_CHANGE_XIAOMEE					0x113C

#define SVR_PROTO_GET_PASTURE						0x11C6
#define SVR_PROTO_CAPTURE_ANIMAL					0x11C8
#define SVR_PROTO_PASTURE_ADD_FEED					0x11C9
#define SVR_PROTO_HERD_ANIMAL						0x11CA
#define SVR_PROTO_PASTURE_GET_ANIMAL				0x10CC
#define SVR_PROTO_PASTURE_ADD_WATER					0x11CB
#define SVR_PROTO_ADD_PASTURE_VISITOR				0X11CD
#define SVR_PROTO_LIST_RECENT_PASTURE_VISITOR 		0x10CE
#define SVR_PROTO_SET_PASTURE_ITEMS					0x11BF
#define SVR_PROTO_GET_STOREHOUSE_ITEM				0x10DE
#define SVR_PROTO_PASTURE_LOCK						0x3101
#define SVR_PROTO_ANIMAL_OUTGO						0x3102
#define SVR_PROTO_ANIMAL_CHICAO						0x3103

#define SVR_PROTO_SHEEP_OUTPUT_NUM					0x10C3
#define SVR_PROTO_RELEASE_ANIMAL					0x11AE
//happy card
#define SVR_PROTO_SET_HAPPY_CARD					0x3109
#define SVR_PROTO_GET_HAPPY_CARD					0x300C
#define SVR_PROTO_TRADE_HAPPY_CARD					0x310A
#define SVR_PROTO_GET_TRADE_HAPPY_CARD_INFO			0x3008
#define SVR_PROTO_GET_HAPPY_CLOTH					0x310B
#define SVR_PROTO_SET_CLASS_MEMBER_REWARD			0xB556
#define SVR_PROTO_SET_CLASS_REWARD					0x10BE

//tmp
#define SVR_PROTO_REQ_TMP_SUPERLAMN					0xB539
#define SVR_PROTO_REQ_TMP_SUPERLAMN_STAT			0xB438
#define SVR_PROTO_GET_CLASS_QUESTION_STAT			0xB454
#define SVR_PROTO_SUBMIT_CLASS_QUESTION				0xB553
#define SVR_PROTO_GET_CLASS_QUESTION_INFO			0xB455
#define SVR_PROTO_ENABLE_TMP_SUPERLAMN				0x2007

#define SVR_PROTO_SPORT_SIGN						0xB520
#define SVR_PROTO_GET_SPORT_TEAM					0xB421
#define SVR_PROTO_SPORT_RAND_SIGN					0xC115
#define SVR_PROTO_SPORT_ADD_MEDAL					0xB522
#define SVR_PROTO_SPORT_ADD_TEAM_MEDAL				0xC117
#define SVP_PROTO_GET_NPC_INFO						0xC016
#define SVR_PROTO_SPORT_SET_TASK					0xB544
#define SVR_PROTO_SPORT_GET_TASK					0xB445
#define SVR_PROTO_SPORT_TEAM_HISTORY				0xC018
#define SVR_PROTO_SPORT_WATER_TREE					0xB546
#define SVR_PROTO_SPORT_WATER_CNT					0xB447
#define SVR_PROTO_SYS_ADD_TEAM_MEDAL				0xC119

#define SVR_PROTO_UPDATE_GAME_BEST_GRADE			0x8100
#define SVR_PROTO_GET_GRADE_LIST_BY_GID				0x8001
#define SVR_PROTO_GET_GRADE_LIST_BY_UID				0x8002
#define SVR_PROTO_UPDATE_PK_FLAG					0x8103
#define SVR_PROTO_GET_PK_SCORE						0x8004
#define SVR_PROTO_SET_GAME_KING						0x1135

#define SVR_PROTO_ADD_PK_INFO						0xB55A
#define SVR_PROTO_GET_PK_LIST						0xB45B
//#define SVR_PROTO_SPORT_WATER_CNT					0xB447

#define SVR_PROTO_SET_LAHM_DIARY					0x3111
#define SVR_PROTO_GET_DIARY_TITLE					0x3012
#define SVR_PROTO_DELETE_DIARY						0x3113
#define SVR_PROTO_SET_DIARY_LOCK					0x3114
#define SVR_PROTO_SEND_FLOWER						0x3115
#define SVR_PROTO_GET_LAHM_DIARY					0x3016
#define SVR_PROTO_SET_BIG_LOCK						0x3117
#define SVR_PROTO_GET_BIG_LOCK						0x3018
#define SVR_PROTO_GET_DIARY_NUM						0x3019

#define SVR_PROTO_ADD_WORK_NUM						0xB523
#define SVR_PROTO_GET_WORK_NUM						0xB424

#define SVR_PROTO_SET_ENGINEER_LEVEL				0x103E

#define SVR_PROTO_MODIFY_SEND_GIFT_CNT				0xB50A
#define SVR_PROTO_GET_SEND_GIFT_CNT					0xB40B


//closet
#define SVR_PROTO_SET_CLOSET						0x118A
#define SVR_PROTO_UNSET_CLOSET						0x118B
#define SVR_PROTO_GET_CLOSET						0x108C

#define SVR_PROTO_CLASS_ADD_SCORE					0x1194
#define SVR_PROTO_CLASS_GET_SCORE					0x1095

#define SVR_PROTO_ADD_CLASS_SCORE_TIMES				0xB50E
#define SVR_PROTO_ADD_TANGGUO_TIMES					0xB50C
#define SVR_PROTO_GET_CANDY_TIMES					0xB408
#define SVR_PROTO_ADD_CANDY_TIMES					0xB507

#define SVR_PROTO_RACE_SIGN							0xB513
#define SVR_PROTO_RACE_ADD_USER_SCORE				0xB514
#define SVR_PROTO_RACE_UPDATE_SCORE					0xC108
#define SVR_PROTO_RACE_UPDATE_RACE					0xC109
#define SVR_PROTO_RACE_GET_TEAM_RACE_LIST			0xC00A
#define SVR_PROTO_RACE_GET_TEAM_SCORE_LIST			0xC00B
#define SVR_PROTO_RACE_GET_RACE_INFO				0XB416
#define SVR_PROTO_RACE_GET_TODAY_SCORE				0xB417
#define SVR_PROTO_RACE_DESC_RACE					0xB518
#define SVR_PROTO_RACE_GET_TEAM						0xB419

#define SVR_PROTO_SET_DRIVE_TIME					0x3126
//car
#define SVR_PROTO_BUY_CAR							0x3120
#define SVR_PROTO_CHG_CAR_ATTI						0x3121
#define SVR_PROTO_CHG_CAR_SLOT						0x3122
#define SVR_PROTO_GARAGE_LIST						0x3023
#define SVR_PROTO_CAR_REFUEL						0x3124
#define SVR_PROTO_CAR_INFO							0x3025
#define SVR_PROTO_SET_SHOW_CAR						0x3127
#define SVR_PROTO_SHOW_CAR_INFO						0x3028
#define SVR_PROTO_SET_CAR_SKILL						0x3129
#define SVR_PROTO_CHG_CAR_ADDON						0x312A
#define SVR_PROTO_CHECK_CAR							0x302B

#define SVR_PROTO_ADD_XUANFENG_HUIZHANG				0xB51A

#define SVR_PROTO_CANDY_MAKE						0xB51C
#define SVR_PROTO_CANDY_GET							0xB51D

#define SVR_PROTO_CANDY_STATUS						0xB41E

#define SVR_QUERY_ITEM_COUNT						0x108F
#define SVR_PROTO_GET_ITEM_ARRAY					0x1040

#define SVR_PROTO_PASTURE_CATCH_FISH				0x3104
#define SVR_PROTO_PASTURE_GET_NETS_STATUS			0x3006
#define SVR_PROTO_PASTURE_GET_NETS					0x3105
#define SVR_PROTO_CANDY_PROP						0xB526
#define SVR_PROTO_GET_CANDY_COUNT					0xB427
#define SVR_PROTO_SUB_VIP_CANDY						0xB529
#define SVR_PROTO_GET_BIBO_INFO						0xC017

#define SVR_PROTO_ADD_CULTI_BREED_EXP				0x1138
#define SVR_UPDATE_NPC_LOVELY						0x310E
#define SVR_PROTO_GET_USER_SKILL 					0x301C

#define SVR_PROTO_SET_DAN							0x3130
#define SVR_PROTO_FUDAN								0x3131
#define SVR_PROTO_GET_FUDAN_TIMES					0x3032

#define SVR_PROTO_CUT_YANGMAO						0x311D
#define SVR_PROTO_START_SHENG_RABIT					0x3140
#define SVR_PROTO_GET_LITTLE_RABIT_INFO				0x3044
#define SVR_PROTO_SET_ANIMAL_FLAG					0x3145
#define SVR_PROTO_IS_RABIT_SHENG					0x3043
#define SVR_PROTO_BREAK_EGG							0x3139

#define SVR_PROTO_TAKE_NPC_TASK						0x3133
#define SVR_PROTO_FIN_NPC_TASK						0x3134
#define SVR_PROTO_GET_NT_CLIENT_DATA				0x3035
#define SVR_PROTO_SET_NT_CLIENT_DATA				0x3136
#define SVR_PROTO_GET_NPC_TASK_STATUS				0x3037
#define SVR_PROTO_GET_NPC_TASKS						0x3038
#define SVR_PROTO_GET_LITTLE_RABIT					0x3141
#define SVR_PROTO_CANCEL_NPC_TASK					0x313F

#define SVR_PROTO_DEL_MULTI_ITEM					0x313D
#define SVR_PROTO_SET_LAMU_CHANGE_VALUE				0x3157
#define SVR_PROTO_SET_PET_BIT_FLAG					0x319C

#define SVR_PROTO_UPDATE_SCORE						0xB557
#define SVR_PROTO_GET_SCORE							0xB458

#define SVR_PROTO_SET_PHOTO_DRESS					0x311E
#define SVR_PROTO_GET_PHOTO_DRESS					0x301F
#define SVR_PROTO_SET_PHOTO_DAHEZHAO				0x11E0
#define SVR_PROTO_GET_PHOTO_DAHEZHAO				0x10E1

#define SVR_PROTO_SET_TYPE_PHOTO_HEZHAO				0x3651
#define SVR_PROTO_GET_TYPE_PHOTO_HEZHAO				0x3650

#define SVR_PROTO_SET_FASHION						0x11A5

#define SVR_PROTO_SET_MODEL_WEAR					0x11A6
#define SVR_PROTO_GET_MODEL_WEAR					0x10A7
#define SVR_PROTO_SET_MOLE_MODEL_WEAR				0x11A8
#define SVR_PROTO_SET_MODEL_MOLE_WEAR				0x11A9

#define SVR_PROTO_SET_CAKE_TIMES					0xB55E
#define SVR_QUERY_MODLE_INDEX						0x11AA

#define SVR_PROTO_SET_NUM_TYPE						0xB50C
#define SVR_PROTO_GET_NUM_TYPE						0xB40D
#define SVR_PROTO_GET_ALL_FISH						0xB45F

#define SVR_PROTO_GET_TUJIAN						0x10AC
#define SVR_PROTO_WEIGHTING							0xB560
#define SVR_PROTO_UPDATE_MAX_WEIGHT					0xC10F

#define SVR_PROTO_PUT_ON_PET_ITEM					0x1158

#define SVR_PROTO_YOUYOU_ADD_ANIMAL					0xC10D
#define SVR_PROTO_GET_LIMIT_ITEM_NUM				0xC00E
#define SVR_PROTO_GET_RING_FRON_OTHER				0xB50F

#define SVR_PROTO_UPDATE_CHRISTMAS_WISH				0xB52B
#define SVR_PROTO_GET_CHRISTMAS_WISH				0xB42C
#define SVR_PROTO_SET_YUANXIAO_WISH					0xB52D
#define SVR_PROTO_GET_YUANXIAO_WISH					0xB42E

#define SVR_PROTO_CHANGE_GIFT_NUM					0xB502
#define SVR_PROTO_GET_GIFT_NUM						0xB415
#define SVR_PROTO_ADD_SEND_GIFT_LIST				0xB513
#define SVR_PROTO_GET_GIFT_FROM_BILU				0xB414
#define SVR_PROTO_ADD_NENGLIANG_CNT					0xB561
#define SVR_PROTO_GET_NENGLIANG_CNT					0xB462
#define SVR_PROTO_GET_CRRRY_ROCK_NUM				0XB463
#define SVR_PROTO_SET_CRRRY_ROCK_NUM				0XB564
#define SVR_PROTO_GET_TEMPLE						0XB471
//#define SVR_PROTO_ADD_LOGIN_INFO					0x3D00
#define SVR_PROTO_ADD_LOGIN_INFO					0xA125

#define SVR_PROTO_GET_PET_TASK_LIST_EX				0x10EF
#define SVR_PROTO_GET_ITEM_BY_USER_SKILL			0xB572
#define SVR_PROTO_QUIT_MACHINE_DOG					0x3166
#define SVR_PROTO_FEED_MACHINE_DOG					0x3167
#define SVR_PROTO_GET_DOG_DO_THING_INFO				0x3068
#define SVR_PROTO_GET_MILK_FROM_COW					0x3172
#define SVR_PROTO_SET_ONLY_ONE_FLAG					0x3173
#define SVR_PROTO_SET_SENDMAIL_FLAG					0x3174
#define SVR_PROTO_GET_EVENT_RECHARGE_MONTHS			0x3076

#define SVR_PROTO_UPDATE_WO_WEI_HUI_SCORE			0xB573
#define SVR_PROTO_GET_WO_WEI_HUI_SCORE				0xB474
#define SVR_PROTO_GET_DELICOUS_FOOD					0XB576
#define SVR_PROTO_SHARE_DELICOUS_FOOD				0XB575

#define SVR_PROTO_CREATE_BUILDING					0x2301
#define SVR_PROTO_GET_MAP_BUILDING_INFO				0x2202
#define SVR_PROTO_GET_MAP_LAST_GRID_ID				0x2205

#define SVR_PROTO_CHANGE_BUILDING_NAME				0x2303
#define SVR_PROTO_CHANGE_BUILDING_STYLE				0x2304
#define SVR_PROTO_ADD_BUILDING_TO_USER				0x3178
#define SVR_PROTO_SET_BD_NAME_IN_USER				0x3180
#define SVR_PROTO_SET_BD_STYLE_IN_USER				0x3181
#define SVR_PROTO_SET_INNER_STYLE_IN_USER			0x3182
#define SVR_PROTO_GET_SHOP_INFO						0x3083
#define SVR_PROTO_LIST_EMPLOYEE						0x3092
#define SVR_PROTO_GET_BOARD_INFO					0x3093
#define SVR_PROTO_GET_PET_EMPLOYED_LIST				0x3095

#define SVR_PROTO_ADD_EMPLOYEE						0x3184
#define SVR_PROTO_DEL_EMPLOYEE						0x3185
#define SVR_PROTO_COOKING_DISH						0x3186
#define SVR_PROTO_PUT_DISH_IN_BOX					0x3187
#define SVR_PROTO_EAT_DISH							0x3188
#define SVR_PROTO_CLEAN_DISH						0x3189
#define SVR_PROTO_CHANGE_DISH_STATE					0x3190
#define SVR_PROTO_SUB_EVALUATE						0x318A
#define SVR_PROTO_SET_SHOP_LEVEL					0x318B
#define SVR_PROTO_GET_SHOP_COUNT					0x318C
#define SVR_PROTO_SET_HONOR_BIT						0x318D
#define SVR_PROTO_SET_PET_EMPLOYED_UID				0x3194
#define SVR_PROTO_GET_REPUTATION					0xB477
#define SVR_PROTO_CHECK_ANIMAL						0x309B
#define SVR_PROTO_ADD_SHOP_EXP						0x318E
#define SVR_PROTO_ADD_SHOP_MONEY					0x318F
#define SVR_PROTO_ADD_SHOP_EVENT_COUNT				0x319D
#define SVR_PROTO_ADD_MONEY_NOT_LIMIT				0x319E

#define SVR_PROTO_GET_DISH_COUNT					0x3098

#define SVR_PROTO_GET_DISH_LEVEL					0x309F
#define SVR_PROTO_SET_DISH_LEVEL					0x31A0
#define SVR_PROTO_INIT_NEW_CARD						0x31A4
#define SVR_PROTO_GET_DISH_LEVEL_ALL				0x30A9

#define SVR_PROTO_SET_LAHM_TEAM						0xB578
#define SVR_PROTO_GET_LAHM_TEAM						0xB479
#define SVR_PROTO_ADD_TEAM_SPORT_SCORE				0xC132
#define SVR_PROTO_GET_SPORT_TEAM_SCORE				0xC033
#define SVR_PROTO_GET_SPORT_TEAM_MEDAL				0xC034
#define SVR_PROTO_GET_STH_FOR_MAX_TEAM				0xC135
#define SVR_PROTO_ADD_MEDAL_FOR_SELF 				0xB57C
#define SVR_PROTO_ADD_MEDAL_FOR_TEAM				0xC136
#define SVR_PROTO_GET_TOP_PET_SCORE					0xC037
#define SVR_PROTO_GET_SELF_MEDAL_NUM				0x0

#define SVR_PROTO_GET_TYPE_DATA						0xC03A
#define SVR_PROTO_SET_TYPE_DATA						0xC139
#define SVR_PROTO_ADD_SEVERAL_CARD					0x31B2

#define SVR_PROTO_GET_TEAM_PRIZE_1					0xB484
#define SVR_PROTO_GET_TEAM_PRIZE_2					0xC038

#define SVR_PROTO_SET_LAHM_PRIZE_F					0xB582
#define SVR_PROTO_SET_MOLE_PRIZE_F					0xB583

#define	SVR_PROTO_GET_NEW_CARD						0x30A3
#define	SVR_PROTO_ADD_SIG_CARD						0x31A5
#define	SVR_PROTO_GIVE_DISH_NPC						0x3196
#define SVR_PROTO_GET_USER_DISH_ALL					0x3097
#define SVR_PROTO_GET_GUA_GUA_CARD_NUM				0xB486
#define SVR_PROTO_GET_MONEY_BY_CARD					0xB585
#define SVR_PROTO_GET_DRAGON_BAG					0x30AE
#define SVR_PROTO_CALL_DRAGON						0x31B0
#define SVR_PROTO_SET_DRAGON_NAME					0x31B3
#define SVR_PROTO_GET_BROOD_EGG_TIME				0x30B4
#define SVR_PROTO_GET_CALLED_DRAONG_INFO			0x30B7
#define SVR_PROTO_RELEASE_DRAGON					0x31B1
#define SVR_PROTO_FEED_DRAGON						0x31AF
#define SVR_PROTO_QUICK_BROOD_EGG					0x31AC
#define SVR_PROTO_TAKE_LITTLE_DRAGON				0x31AD
#define SVR_PROTO_BROOD_DRAGON_EGG					0x31AB


#define SVR_PROTO_CHECK_SESSION_TW					0x0B02

#define SVR_PROTO_CHECK_SESSION						0xA024

//#define SVR_PROTO_CHECK_SESSION					0xA033


#define SVR_PROTO_CHECK_USERID_EXSIT				0x0005

#define SVR_PROTO_GET_BUSINESSMAN_GOODS				0xB487
#define SVR_PROTO_BUY_BUSINESSMAN_GOODS				0xB588
#define SVR_PROTO_GET_FIRE_CUP_NUM					0xB41F
#define SVR_PROTO_GET_FIRE_CUP_TEAM_MEDAL			0xC021
#define SVR_PROTO_GET_FIRE_CUP_PRIZE				0xB532

#ifdef TW_VER
    #define SVR_PROTO_GET_SESSION					0x0B01
#else
    #define SVR_PROTO_GET_SESSION					0xA122
#endif

#define SVR_PROTO_GET_NEW_CARD_EXP					0x30A7
#define SVR_PROTO_GET_LAMU_COUNT_STATE				0x30BF

//friendship box
#define SVR_PROTO_GET_FRIEND_BOX_ITEMS				0x30B9
#define SVR_PROTO_GET_FRIEND_BOX_HISTORY			0x30BA
#define SVR_PROTO_PUT_ITEM_TO_FRIEND_BOX			0x31BB
#define SVR_PROTO_GET_ITEM_FROM_FRIEND_BOX			0x31BC
#define SVR_PROTO_CHECK_ITEM_FROM_FRIEND			0x30BD
#define SVR_PROTO_SET_TAG_ITEM_FROM_FRIEND			0x31BE

//machine work friendship box
#define SVR_PROTO_MW_GET_FRIEND_BOX_ITEMS			0x3629
#define SVR_PROTO_MW_GET_FRIEND_BOX_HISTORY			0x362A
#define SVR_PROTO_MW_PUT_ITEM_TO_FRIEND_BOX			0x362B
#define SVR_PROTO_MW_GET_ITEM_FROM_FRIEND_BOX		0x362C
#define SVR_PROTO_MW_CHECK_ITEM_FROM_FRIEND			0x362D
#define SVR_PROTO_MW_SET_TAG_ITEM_FROM_FRIEND		0x362E


//lahm classroom
#define SVR_PROTO_CREATE_CLASSROOM					0x2311
#define SVR_PROTO_SET_CLASSROOM_NAME				0x2312
#define SVR_PROTO_SET_CLASSROOM_STYLE				0x2313
#define SVR_PROTO_GET_FRAME_CLASSROOM				0x2214
#define SVR_PROTO_GET_LAST_FRAMEID					0x2215
#define SVR_PROTO_GET_RAND_USERID					0x2217
#define SVR_PROTO_CLASSROOM_SET_TEACHER_EXP			0x2318
#define SVR_PROTO_CLASSROOM_SET_OUTSTAND_SUM		0x2319
#define SVR_PROTO_GET_FRIEND_CLASSROOM_INFO			0x221A
#define SVR_PROTO_CLASSROOM_SET_EXP_AND_OUTSTAND_SUM	0x231B

#define SVR_PROTO_USER_CLASSROOM_CREATE_CLASSROOM	0x31C1
#define SVR_PROTO_USER_CLASSROOM_SET_NAME			0x31C2
#define SVR_PROTO_USER_CLASSROOM_SET_INNER_STYLE	0x31C3
#define SVR_PROTO_USER_CLASSROOM_SET_GRADE			0x31C4
#define SVR_PROTO_USER_LAMU_CLASSROOM_ADD_LAMUS		0x31C5
#define SVR_PROTO_USER_CLASSROOM_ABANDON_LAMUS 		0x31C6
#define SVR_PROTO_USER_CLASSROOM_GET_CLASS_INFO		0x30C7
#define SVR_PROTO_USER_CLASSROOM_GET_LAMUS_INFO		0x30C8
#define SVR_PROTO_USER_CLASSROOM_GET_TEACHER_INFO	0x30C9
#define SVR_PROTO_USER_CLASSROOM_ADD_COURSE_CNT		0x31CA
#define SVR_PROTO_USER_CLASSROOM_CHECK_ADD_COURSE	0x30CB
#define SVR_PROTO_USER_CLASSROOM_GET_REMEMBRANCE	0x30CD
#define SVR_PROTO_USER_CLASSROOM_GET_TEACH_PLAN		0x30CE
#define SVR_PROTO_USER_CLASSROOM_CLASS_BEGIN		0x31CF
#define SVR_PROTO_USER_CLASSROOM_SET_TEACH_MODE		0x31D0
#define SVR_PROTO_USER_CLASSROOM_CLASS_END			0x31D1
#define SVR_PROTO_USER_CLASSROOM_GET_BASE_TEACH_INFO	0x30D2
#define SVR_PROTO_USER_CLASSROOM_GET_COURSE_NUM		0x30D3
#define SVR_PROTO_USER_CLASSROOM_GET_COURSE_INFO	0x30D4
#define SVR_PROTO_USER_LAMU_CLASSROOM_EXAM			0x31D5
#define SVR_PROTO_USER_CLASSROOM_GET_EXAM_INFO		0x30D6
#define SVR_PROTO_USER_CLASSROOM_GET_CLASSROOM_COUNT	0x30D7
#define SVR_PROTO_USER_CLASSROOM_SET_PRIZE_ITEM		0x31D8
#define SVR_PROTO_USER_CLASSROOM_GET_CLASS_FLAG		0x30D9
#define SVR_PROTO_USER_CLASSROOM_CLASS_GRADUATE		0x31DA
#define SVR_PROTO_USER_CLASSROOM_ADD_TEACHER_ATTR	0x31DB
#define SVR_PROTO_USER_CLASSROOM_SET_PET_MOOD		0x31DC
#define SVR_PROTO_USER_CLASSROOM_UPDATE_LAMU_ATTR	0x31DD
#define SVR_PROTO_USER_CLASSROOM_ADD_COURSE_SCORE	0x31DF
#define SVR_PROTO_USER_CLASSROOM_ADD_LESSON_EVENT	0x31E1
#define SVR_PROTO_USER_CLASSROOM_SET_HONOR_BIT		0x31E2
#define SVR_PROTO_USER_LAMU_CLASSROOM_ADD_LAMU_ATTRS	0x31E3
#define SVR_PROTO_USER_CLASSROOM_DO_FELLOWSHIP 		0x31E4


#define SVR_PROTO_ADD_GET_ITEM_RECORD				0x31E7
#define SVR_PROTO_GET_ITEM_HISTORY_RECORD			0x30E8
#define SVR_PROTO_CHECK_ITEM_GIVE_FRIEND			0x30E9






#define SVR_PROTO_SYSARG_AUCTION_ADD_ONE_RECORD		0xC13E
#define SVR_PROTO_SYSARG_AUCTION_GET_ATTIREID_AND_TIME	0xC03D
#define SVR_PROTO_SYSARG_DONATE_ITEM_AND_XIAOMEE	0xC13F
#define SVR_PROTO_SYSARG_CONTRIBUTE_GET_RANK		0xC040
#define SVR_PROTO_SYSARG_QUERY_CHARITY_DRIVE		0xC041

#define SVR_PROTO_SYSARG_ADD_RANK_TYPE_COUNT		0xC143
#define SVR_PROTO_SYSARG_GET_TYPE_RANK				0xC042
#define SVR_PROTO_SYSARG_DEC_RANK_TYPE_COUNT		0xC144
#define SVR_PROTO_SYSARG_GET_TYPE_RANK_COUNT_INFO	0xC045
#define SVR_PROTO_SYSARG_ADD_ANIMAL_SKILL_COUNT		0xC146
#define SVR_PROTO_SYSARG_DEC_ANIMAL_SKILL_COUNT		0xC147
#define SVR_PROTO_SYSARG_GET_USE_SKILL_INFO			0xC048


#define SVR_PROTO_SYSARG_GET_DAYTYPE_COUNT			0xC064

#define SVR_PROTO_SYSARG_GET_GOLD_COMPASS_DATA		0xC065
#define SVR_PROTO_SYSARG_SET_GOLD_COMPASS_DATA		0xC166
#define SVR_PROTO_SYSARG_GET_GOLD_USERS_INFO		0xC067

#define SVR_PROTO_SYSARG_ADD_GUESS_PRICE_INFO		0xC16A
#define SVR_PROTO_SYSARG_GUESS_RIGHT_USER_INFO		0xC06B



#define SVR_PROTO_FRAMEWORK_NOTIFY_USER_IP			0xC080

#define SVR_PROTO_ROOMINFO_GET_RANDOM_GAIN_TIMES	0xB433
#define SVR_PROTO_ROOMINFO_CHANGE_RANDOM_GAIN_TIMES	0xB534


#define SVR_PROTO_GET_BEAN_LOTTERY_COUNT			0xB489
#define SVR_PROTO_SET_BEAN_LOTTERY_COUNT			0xB58A

#define SVR_PROTO_DEC_USED_MIBI						0xB58B
#define SVR_PROTO_GET_USED_MIBI_COUNT				0xB48D

#define SVR_PROTO_ROOMINFO_ADD_CHRISTMAS_SOCK		0xB58E
#define SVR_PROTO_ROOMINFO_GET_CHRISTMAS_SOCK_INFO	0xB48F
#define SVR_PROTO_ROOMINFO_DEL_CHRISTMAS_SOCK_INFO	0xB590
#define SVR_PROTO_ROOMINFO_GET_CHRIS_CAKE_INFO		0xB494
#define SVR_PROTO_ROOMINFO_DONE_CHRIS_CAKE			0xB595
#define SVR_PROTO_ROOMINFO_GIVE_CAKE_TO_NPC			0xB596
#define SVR_PROTO_ROOMINFO_GET_CHRIS_CAKE_SCORE		0xB493
#define SVR_PROTO_ROOMINFO_EXCHANGE_STH_BY_CAKE_SCORE	0xB592
#define SVR_PROTO_ROOMINFO_GET_FOOTPRINT_COUNT		0xB499
#define SVR_PROTO_ROOMINFO_EXCHANGE_FOOTPRINT		0xB598
#define SVR_PROTO_ROOMINFO_FOOTPRINT_ADD_COUNT		0xB597
#define SVR_PROTO_ROOMINFO_GET_LOGIN_BONUS_INFO		0xB59A
#define SVR_PROTO_ROOMINFO_GET_LOGIN_WEEKEND_COUNT	0xB49D
#define SVR_PROTO_ROOMINFO_UPDATE_WEEKEND_COUNT		0xB59E

#define SVR_PROTO_USER_SEND_TIME_MAIL				0x3379
#define SVR_PROTO_USER_GET_TIME_MAIL				0x327A
#define SVR_PROTO_USER_SEND_TIME_ITEM				0x337B
#define SVR_PROTO_USER_GET_TIME_ITEM				0x337C
#define SVR_PROTO_USER_GET_MAIL_ITEM_COUNT			0x327D


#define SVR_PROTO_GET_BEAN_MALL_LOGIN_TIMES			0x3326


#define SVR_PROTO_GET_ANIMAL_LVL					0x30EA
#define SVR_PROTO_FARM_ANIMAL_USE_ITEM				0x31EB
#define SVR_PROTO_GET_ANIMAL_USED_SKILL_INFO		0x30EC
#define SVR_PROTO_FARM_ANIMAL_USE_SKILL				0x31ED
#define SVR_PROTO_GET_ANIMAL_BASE_INFO				0x30EE
#define SVR_PROTO_GET_TRAIN_KAKU_NIAN_INFO			0xB49B
#define SVR_PROTO_ADD_TRAIN_KAKU_NIAN_COUNT			0xB59C
#define SVR_PROTO_GET_VERY_GOOD_ANIMAL_COUNT		0x30EF

//拉取天使乐园
#define SVR_PROTO_USER_GET_PARADISE					(0x30F0)
//更换家园背景
#define SVR_PROTO_USER_CHANGE_PARADISE_BACKGOUND	(0x31F1)
//改变天使种子位置
#define SVR_PROTO_USER_CHANGE_ANGEL_POS				(0x31F2)
//更新天使乐园物品列表
#define SVR_PROTO_USER_PARADISE_SET_ATTIRELIST		(0x31F3)
//补充灵气
#define SVR_PROTO_USER_PARADISE_SET_NIMBUS			(0x31F4)
//签订契约
#define SVR_PROTO_USER_ANGEL_SIGN_CONTRACT			(0x31F5)
//天使放生
#define SVR_PROTO_USER_ANGEL_FREE					(0x31F6)
//获取天使乐园访客列表
#define SVR_PROTO_USER_PARADISE_GET_VISITLIST		(0x30F7)
//获取天使乐园仓库物品
#define SVR_PROTO_USER_PARADISE_STORE_ITEM			(0x30F8)
//扣除物品
#define SVR_PROTO_USER_DEL_ATTIRE_ANGEL_TOOL		(0x31F9)

//查询天使图鉴
#define SVR_PROTO_USER_GET_CONTRACT_ANGLES			(0x30FA)
//放生已捕获的天使
#define SVR_PROTO_USER_TERMINATE_CONTRACT			(0x31FB)

//让天使跟随
#define SVR_PROTO_MAKE_ANGEL_FOLLOWED				(0x30FC)

//热点统计
#define SVR_PROTP_HOT_STATISTICS					(0xC14A)

//拉取好友天使园信息
#define SVR_PROTO_GET_FRIEND_PARAIDSE_INFO			(0xC04C)

//圣光兽转生
#define SVR_PROTO_CHANGE_TO_ANGEL					(0x31FF)

//来去访客天使信息
#define SVR_PROTO_GET_VISTOR_ANGEL_INFO				(0xC04D)

//净化天使
#define SVR_PROTO_USER_CAPTURE_ANGEL_CMD			(0x3301)
//添加访客信息
#define SVR_PROTO_ADD_PARADISE_VISTOR				(0x3302)
//获得医院天使
#define SVR_PROTO_ANGEL_IN_HOSPITAL					(0x3203)
//使用王子之泪
#define SVR_PROTO_USE_TRAR							(0x3304)
//获取热点信息
#define SVR_PROTO_GET_HOT_ITEM						(0xC049)
//更新用户全局天使信息
#define SYSARG_UPDATE_PARADISE_RANK_CMD				(0xC14B)
//使用道具
#define SVR_USE_PARADISE_PROP						(0x3305)
//获取战斗天使
#define SVR_PROTO_GET_FIGHT_ANGEL					(0x3206)
//战斗结束
#define SVR_PROTO_FIGHT_END							(0x3307)
//获取战斗等级
#define SVR_PROTO_FIGHT_LEVEL						(0x3208)
//获取战斗得分
#define SVR_PROTO_FIGHT_SCORE						(0x3209)
//出院
#define SVR_PROTO_LEAVE_HOSPITAL					(0x330a)

//领取赠送的天使
#define SVR_PROTO_ADD_ANGEL							(0X330B)
//angel favorite
#define SVR_PROTO_ANGEL_SHOW						(0x330D)
#define SVR_PROTO_ANGEL_GET_FAVORITE_INFO			(0x320C)
#define SVR_PROTO_GET_BACKGROUND_ID					(0x320E)

#define SVR_PROTO_EXCHANGE_DAVIS_BEAN				(0x330F)
#define SVR_PROTO_GET_ANGEL_HONORS					(0x3210)
#define SVR_PROTO_SET_ANGEL_HONORS					(0x3311)

//地下城挖宝
#define	SVR_PROTO_DUNGEON_BEGIN_EXPLORE				(0x3312)
#define	SVR_PROTO_DUNGEON_GET_BAG_INFO				(0x3218)
#define	SVR_PROTO_DUNGEON_USE_ITEM					(0x3316)
#define	SVR_PROTO_DUNGEON_UPDATE_HP_EXP				(0x3315)
#define	SVR_PROTO_DUNGEON_UPDATE_MAP_INFO			(0x3317)
//珍宝库
#define SVR_PROTO_DUNGEON_GET_EXHIBIT_INFO			(0x331E)
#define SVR_PROTO_DUNGEON_GET_STORAGE_INFO			(0x321D)
#define SVR_PROTO_DUNGEON_SET_EXHIBIT_ITEM			(0x331F)
#define SVR_PROTO_DUNGEON_SWAP_EXHIBIT_ITEM			(0x3321)
#define SVR_PROTO_DUNGEON_GET_VISITOR_INFO			(0x3222)
#define SVR_PROTO_DUNGEON_GET_VISITOR_FULL_INFO		(0xC04F)
#define SVR_PROTO_DUNGEON_GET_FRIEND_INFO			(0xC050)

#define SVR_PROTO_DUNGEON_SET_BACKGROUND			(0x3325)
#define SVR_PROTO_DUNGEON_SET_EXHIBIT_STATE			(0x3324)
#define SVR_PROTO_DUNGEON_ADD_VISITOR				(0x3323)

//更新珍宝库等级全局表
#define SVR_PROTO_DUNGEON_COMMIT_LEVEL				(0xC14E)

//Angry Lahm
#define SVR_PROTO_AL_UPDATE_SCORE					(0xB59F)
#define SVR_PROTO_AL_GET_TASK_INFO					(0xB47A)

#define SVR_PROTO_HAS_GAME_OVER						(0x3327)
//angel fight
#define SVR_PROTO_AF_GET_USER_BASE_INFO				(0x3240)
#define SVR_PROTO_AF_GET_ALL_SKILL					(0x3241)
#define SVR_PROTO_AF_GET_USER_PACKAGE				(0x3242)
#define SVR_PROTO_AF_GET_ALL_CARD 					(0x3243)
#define SVR_PROTO_AF_USE_ITEM						(0x3344)
#define SVR_PROTO_AF_USE_CARD						(0x3346)
#define SVR_PROTO_AF_LEVEL_UP						(0x3347)
#define SVR_PROTO_AF_CHANGE_EQUIP					(0x3348)
#define SVR_PROTO_AF_GET_ALL_FRIENDS				(0x221C)
#define SVR_PROTO_AF_SET_WHOLE_EXP					(0x231D)
#define SVR_PROTO_AF_GET_ALL_FRIENDS_FIGHT			(0x324B)
#define SVR_PROTO_AF_GET_MAP_PASS_POINT				(0x324C)
#define SVR_PROTO_AF_GET_ONE_SKILL					(0x324D)
#define SVR_PROTO_AF_CHECK_GET_PRIZE				(0x334F)
#define SVR_PROTO_AF_USER_GET_PRIZE					(0x3350)
#define SVR_PROTO_AF_USER_GET_SOME_FRIENDS			(0x2220)
#define SVR_PROTO_AF_USER_GET_SOME_FRIENDS_INFO		(0x3252)
#define SVR_PROTO_AF_USER_SET_WISHING				(0x3351)
#define SVR_PROTO_AF_USER_CHECK_WISHING				(0x221E)
#define SVR_PROTO_AF_USER_SET_WISHING_CNT			(0x231F)
#define SVR_PROTO_AF_GET_FRIEND_WISHING_CNT			(0x2222)
#define SVR_PROTO_AF_DEAL_FRIEND_WISHING			(0x3353)
#define SVR_PROTO_AF_SET_FRIEND_WISHING_CNT			(0x2321)
#define SVR_PROTO_AF_GET_FRIEND_EVENT_CNT			(0x2223)
#define SVR_PROTO_AF_DEAL_FRIEND_EVENT				(0x3354)
#define SVR_PROTO_AF_GET_WISH_ITEMID				(0x3255)
#define SVR_PROTO_AF_USER_GET_FIGHT_RECORD			(0x3256)
#define SVR_PROTO_AF_USER_GET_WISHING_COLLECT		(0x3357)
#define SVR_PROTO_AF_USER_SET_EVENT_CNT				(0x2324)
#define SVR_PROTO_AF_GET_DAILY_TASK					(0x3258)
#define SVR_PROTO_AF_SET_DAILY_TASK					(0x3360)
#define SVR_PROTO_AF_CHECK_FINISH_TASK				(0x3361)
#define SVR_PROTO_AF_ADD_FIGHT_EXP					(0x3362)
#define SVR_PROTO_AF_CHECK_REFRESH_TASK				(0x3259)
#define SVR_PROTO_AF_REFRESH_ONE_TASK				(0x3363)
#define SVR_PROTO_AF_GET_FIGHT_BOSS_COUNT			(0x3264)
#define SVR_PROTO_AF_GET_MASTER_AND_APPRENTICE		(0x3265)
#define SVR_PROTO_AF_GET_APPRENTICE_MARKET			(0x2225)
#define SVR_PROTO_AF_GET_APPRENTICE_INFO			(0x3266)
#define SVR_PROTO_AF_GET_MASTER_INFO				(0x3267)
#define SVR_PROTO_AF_CHECK_GET_APPRENTICE			(0x3268)
#define SVR_PROTO_AF_CHECK_APPRENTICE_GET_MASTER	(0x3274)
#define SVR_PROTO_AF_GET_APPRENTICE_TRAINING		(0x3269)
#define SVR_PROTO_AF_USER_TRAIN_APPRENTICE			(0x336A)
#define SVR_PROTO_AF_USER_EXPEL_APPRENTICE			(0x336B)
#define SVR_PROTO_AF_USER_DELETE_MASTER				(0x336C)
#define SVR_PROTO_AF_MONIFY_MASTER					(0x2326)
#define SVR_PROTO_AF_APPRENTICE_RESPECT_MASTER		(0x336D)
#define SVR_PROTO_AF_MASTER_SET_RESPECT				(0x336E)
#define SVR_PROTO_AF_GET_RESPECT_CASH				(0x336F)
#define	SVR_PROTO_AF_APPRENTICE_CHECK_FINISH		(0x3270)
#define SVR_PROTO_AF_MASTER_FINISH_APPRENTICE		(0x3371)
#define SVR_PROTO_AF_APPRENTICE_FINISH_APPRENTICE	(0x3372)
#define SVR_PROTO_AF_GET_MASTER_RECORD				(0x3273)
#define SVR_PROTO_AF_MODIFY_USER_MASTER				(0x3375)
#define SVR_PROTO_AF_USER_GET_LEVEL					(0x3276)
#define SVR_PROTO_AF_USER_ADD_APPRENTICE			(0x3377)
#define SVR_PROTO_AF_ADD_MASTER_APPRENTICE_MSG		(0x3378)
#define SVR_PROTO_AF_GET_PVP_FIGHT_RECORD			(0x3280)
#define SVR_PROTO_AF_GET_PVP_WIN_PRIZE				(0x3381)

#define SVR_PROTO_GET_MONGOLIA_COW_PASTURE			(0x3328)
#define SVR_PROTO_PLAY_WITH_MILK_COW				(0x3329)
#define SVR_PROTO_PLANT_PASTURE_GRASS				(0x332A)
#define SVR_PROTO_PURCHASE_PASTURE_MILK				(0x332B)

#define SVR_PROTO_USER_EAT_MOONCAKE					(0x33D0)
#define SVR_PROTO_USER_GET_MOONCAKE					(0x32D1)

#define SVR_PROTO_USER_GET_LUCKY_TICKET				(0x33D3)
#define SVR_PROTO_USER_CHECK_GET_TICKET				(0x32D4)
#define SVR_PROTO_USER_SWAP_TICKET_PRIZE			(0x33D5)
#define SVR_PROTO_USER_GET_HISTORY_TICKET			(0x32D6)
#define SVR_PROTO_USER_NATIONAL_DAY_LOGIN			(0x32D7)
#define SVR_PROTO_USER_GET_NATIONAL_DAY_GIFT		(0x33D8)

#define SVR_PROTO_GET_ANGEL_COMPOSE 				(0x3219)
#define SVR_PROTO_USER_COMPOSE_NEW_ANGEL			(0x321A)
#define SVR_USER_SYNTHESIS_HISTORY					(0x3313)

#define SVR_PROTO_GET_USER_TASK_EX_IDLIST			(0x32D2)
//for cute pig
#define SVR_PROTO_CUTE_PIG_GET_INFO					(0x33AE)
#define SVR_PROTO_CP_GET_PIG_INFO					(0x32AF)
#define SVR_PROTO_CP_FEED							(0x33B0)
#define SVR_PROTO_CP_RAISE_NEW_PIG					(0x33B1)
#define SVR_PROTO_CP_TRAIN							(0x33B2)
#define SVR_PROTO_CP_TICKLE							(0x33B3)
#define SVR_PROTO_CP_BATHE							(0x33B4)
#define SVR_PROTO_CP_SET_NAME						(0x33B5)
#define SVR_PROTO_CP_SET_FORMATION					(0x33B6)
#define SVR_PROTO_CP_MATE_CHECK						(0x33B7)
#define SVR_PROTO_CP_MATE							(0x33B8)
#define SVR_PROTO_CP_GET_KNAPSACK_INFO				(0x32B9)
#define SVR_PROTO_CP_SALE_PIG						(0x33BA)
#define SVR_PROTO_CP_GET_MALE_PIG_INFO				(0x32BB)
#define SVR_PROTO_CP_SET_GLOBLE_LEVEL				(0xC151)
#define SVR_PROTO_CP_UPDATE_LEVEL					(0x33BC)
#define SVR_PROTO_CP_GET_FRIEND_INFO				(0xC052)
#define SVR_PROTO_CP_GET_TASK_INFO					(0x32BD)
#define SVR_PROTO_CP_ACCEPT_TASK					(0x33BE)
#define SVR_PROTO_CP_SUBMIT_TASK					(0x33BF)
#define SVR_PROTO_CP_GET_NOTICE_INFO				(0x32C0)
#define SVR_PROTO_CP_PROCESS						(0x33C1)
#define SVR_PROTO_CP_GET_RAND_LUCKY					(0x33C2)
#define SVR_PROTO_CP_GET_ILLUSTRATE					(0x32C3)
#define SVR_PROTO_CP_UPGRADE_BUILDING				(0x33C4)
#define SVR_PROTO_CP_USE_ITEM						(0x33C5)
#define SVR_PROTO_CP_STH_DONE						(0x33C6)
#define SVR_PROTO_CP_GET_TICKET						(0x33C7)

#define SVR_PROTO_CP_USE_CARD						(0x33C9)
#define SVR_PROTO_CP_GET_CARD_INFO					(0x32C8)

#define SVR_PROTO_CP_DAREN_VOTE						(0x33CA)
#define SVR_PROTO_CP_GET_DAREN_VOTE					(0x32CD)
#define SVR_PROTO_GET_QUESTIONNAIRE_SUBTYPE			(0xC022)

#define SVR_PROTO_ADD_FRIEND_REQ					(0x33CB)
#define SVR_PROTO_ADD_FRIEND_REP					(0x33CC)

#define SVR_PROTO_GET_CANDY_FREIND_CNT				(0x32D9)
#define SVR_PROTO_GET_CANDY_FROM_FREIND				(0x33CF)
#define SVR_PROTO_GET_CANDY_SHARE_BONUS				(0x33DA)
#define SVR_PROTO_XHX_GET_TASK						(0x33DD)
#define SVR_PROTO_SET_CONTINUE_LOGIN_VALUE			(0x33DE)
#define SVR_PROTO_GET_GUIDER_PRIZE					(0x33E7)
#define SVR_PROTO_LOOK_GUIDER_PRIZE					(0x32E8)

#define SVR_PROTO_GET_AVATAR_LIST					(0x33DF)
#define SVR_PROTO_SAVE_AVATAR						(0x33E0)
#define SVR_PROTO_REMOVE_AVATAR						(0x33E1)

#define SVR_PROTO_CP_SET_BACKGROUND					(0x33E2)

#define SVR_PROTO_GET_TASK_LIST_INFO				(0x32E3)

#define SVR_PROTO_CP_SHOW							(0x33E6)
#define SVR_PROTO_CP_SWAP_PIG						(0x33E9)
#define SVR_PROTO_CP_FOLLOW							(0x33E4)
#define SVR_PROTO_CP_GET_SHOW_STAGE_INFO			(0x32EC)
#define SVR_PROTO_CP_GET_2ND__GAME_INFO				(0x32EA)
#define SVR_PROTO_CP_USE_SHOW_STAGE_ITEM			(0x33EB)
#define SVR_PROTO_CP_SET_CLOTHES					(0x33ED)
#define SVR_PROTO_CP_ADD_ATTR						(0x33EE)
#define SVR_PROTO_CP_FEED_GET_INFO					(0x32EF)

#define SVR_PROTO_CP_SHOW_SET_GAME_STATE			(0xB535)
#define SVR_PROTO_CP_SHOW_GET_ACHIEVE				(0xB536)
#define SVR_PROTO_CP_SHOW_GET_ACHIEVE_INFO			(0xB437)

#define SVR_PROTO_CP_ILLUSTRATE_CHECK				(0x32F5)

#define SVR_PROTO_USER_AS_ADD_TYPE_INT_DATA			(0x33F0)
#define SVR_PROTO_USER_AS_QUERY_TYPE_INT_DATA		(0x32F1)

#define SVR_SYSARG_JOIN_BEAUTY_CONTEND				(0xC153)
#define SVR_SYSARG_GET_BEAUTY_GAME_RECORD			(0xC054)
#define SVR_SYSARG_GET_BEAUTY_GAME_GIFT				(0xC055)
#define SVR_PROTO_HANG_CHRISTMAS_SOCK				(0x33F2)
#define SVR_PROTO_CHECK_CHRISTMAS_SOCK_CNT 			(0x32F4)
#define SVR_PROTO_GET_CHRISTMAS_SOCR_RECORD 		(0x32F3)
#define SVR_PROTO_GET_CHRISTMAS_SOCK_TOP10 			(0xC056)
#define SVR_PROTO_SET_CHRISTMAS_SOCK_TOP10 			(0xC157)
#define SVR_PROTO_CHECK_CHRISTMAS_GIFT				(0x32F6)
#define SVR_PROTO_SET_CHRISTMAS_GIFT				(0x33F7)

//爱心天使慈善派对
#define SVR_PROTO_DONATE_ITEM						(0xC158)
#define SVR_PROTO_GET_AUCTION_LIST					(0xC05A)
#define SVR_PROTO_AUCTION_ITEM						(0xC15B)
#define SVR_PROTO_UPDATE_AUCTION_LIST				(0xC159)

#define SVR_PROTO_SYSARG_MATCHING_MAP 				(0xC15E)
#define SVR_PROTO_SYSARG_DROP_MAP					(0xC15F)
#define SVR_PROTO_SYSARG_GET_MAP					(0xC060)
#define SVR_PROTO_SYSARG_CHECK_PLAYER_NUM			(0xC15D)
#define SVR_PROTO_SYSARG_DEL_PLAYER_NUM				(0xC161)

#define SVR_PROTO_USER_GET_KEY_CHANCE 				(0x33FA)
#define SVR_PROTO_USER_EXPLORE_CLEAR_STATE			(0x33FB)
#define SVR_PROTO_USER_EXPLORE_QUERY_STATE			(0x32FC)
#define SVR_PROTO_CP_GET_ALL_HONOR					(0x32FD)
#define SVR_PROTO_CP_SET_HONOR						(0x33FE)

#define SVR_PROTO_FP_GET_AWARD_STAMP				(0x33FF)

#define SVR_PROTO_WVS_GET_TEAM_POWER				(0xC069)
#define SVR_PROTO_WVS_SET_TEAM_POWER				(0xC168)

#define SVR_PROTO_GET_VIP_ANGEL_INFO				(0x32F8)
#define SVR_PROTO_EXCHANGE_VIP_ANGEL				(0x33F9)

#define SVR_PROTO_USER_GET_SPRINT_FESTIVAL_LOGIN_INFO		(0x3604)
#define SVR_PROTO_USER_GET_SPRINT_FESTIVAL_LOGIN_BONUS		(0x3603)
#define SVR_PROTO_USER_SPRINT_FESTIVAL_LOGIN		(0x3602)
#define SVR_PROTO_USER_VIP_CONTINUE_WEEK_LOGIN		(0x3607)

#define SVR_PROTO_USER_SUBMIT_SPRING_COUPLETS		(0x33FF)
#define SVR_PROTO_USER_GET_SPRING_COUPLETS			(0x3600)
#define SVR_PROTO_USER_SET_COUPLETS_PRIZE 			(0x3601)
#define SVR_PROTO_SET_SYSARG_COUPLETS_INFO			(0xC162)
#define SVR_PROTO_USER_GET_COUPLETS_USERID_LIST 	(0xC063)
#define SVR_PROTO_USER_GET_COUPLETS_PRIZE			(0x3606)
#define SVR_PROTO_YEAR_FEAST_GET_PRIZE				(0x3605)
#define SVR_PROTO_USER_GET_VIP_CONTINUE_WEEK_LOGIN_INFO (0x3608)
#define SVR_PROTO_USER_GET_VIP_WEEK_LOGIN_AWARD      (0x3609)
#define SVR_PROTO_USER_WEEKEND_LOGIN     			(0x360A)
#define SVR_PROTO_USER_GET_WEEKEND_LOGIN_BONUS     (0x360B)
#define SVR_PROTO_USER_GET_WEEKEND_LOGIN_INFO      (0x360C)

#define SVR_PROTO_USER_SET_ITEMID_SCORE         (0x360D)
#define SVR_PROTO_USER_GET_ITEMID_SCORE         (0x360E)
#define SVR_PROTO_USER_CHANGE_ICE_DRAGON        (0x360F)
#define SVR_PROTO_USER_EXCHANGE_PIGLET_HOUSE    (0x3610)

#define SVR_PROTO_USER_GET_CUTEPIG_GOLD_KEY		 (0x3630)
#define SVR_PROTO_USER_GET_PIGLET_MACHINE_WORK    (0x3611)
#define SVR_PROTO_USER_PIG_EXPLOR_MAP_MINE        (0x3612)
#define SVR_PROTO_GET_USER_EXPLOR_MINE_INFO       (0x3614)
#define SVR_PROTO_USER_PIGLET_FINISH_EXPLOR_MINE  (0x3615)
#define SVR_PROTO_CP_USER_PIGLET_MELT_ORE         (0x3613)
#define SVR_PROTO_CP_USER_PIGLET_PRODUCE_MACHINE_PART    (0x3616)
#define SVR_PROTO_USER_PIGLET_FINISH_WORK         (0x3617)
#define SVR_PROTO_USER_GET_PIGLET_WORK_MACHINE    (0x3618)
#define SVR_PROTO_USER_USE_ACCELERATE_TOOL         (0x3619)
#define SVR_PROTO_USER_CP_PRODUCE_SPECIAL_MACHINE   (0x3628)
#define SVR_PROTO_USER_GET_PIGLET_GUIDER_STEP      (0x3620)
#define SVR_PROTO_USER_SET_PIGLET_GUIDER_STEP      (0x3621)

#define SVR_PROTO_USER_GET_GREAT_PRODUCE_ORDER      (0x3622)
#define SVR_PROTO_USER_PUT_GREAT_PRODUCE_ORDER      (0x3624)
#define SVR_PROTO_USER_FINISH_GREAT_PRODUCE_ORDER   (0x3623)
#define SVR_PROTO_USER_THOUSAND_GREAT_PRODUCE_NUMBER (0xC06F)
#define SVR_PROTO_USER_SET_GREAT_PRODUCE_NUMBER     (0xC06E)
#define SVR_PROTO_USER_CP_RANDOM_MACHINE_PRODUCT    (0x3625)
#define SVR_PROTO_GET_KFC_DECORATION           (0x3626)
#define SVR_PROTO_USER_PUT_KFC_DECORATION           (0x3627)
#define SVR_PROTO_USER_GET_POLL_DECORATION          (0xC071)
#define SVR_PROTO_USER_PUT_DECORATION_POLL      (0xC070)
#define SVR_PROTO_USER_CP_TAKE_BACK_MINING       (0x3632) ////

#define SVR_PROTO_USER_CATCH_BUTTERFLY_ANGEL		 (0x3631)


#define SVR_PROTO_SYSARG_SET_ITEMID_SCORE       (0xC16C)

#define SVR_PROTO_USER_MVP_GET_TEAMID		 (0x3640)
#define SVR_PROTO_USER_MVP_SET_TEAMID		 (0x3641)
#define SVR_PROTO_USER_SET_MVP_BADGE		     (0x3642)

#define SVR_PROTO_USER_LEAVE_MVP_TEAM		 (0x3634)
#define SVR_PROTO_USER_ENTER_MVP_TEAM		 (0x3635)
#define SVR_PROTO_USER_CREATE_MVP_TEAM		 (0x3633)
#define SVR_PROTO_USER_DISSOLVE_MVP_TEAM	 (0x3636)
#define SVR_PROTO_USER_GET_MVP_TEAM_INFO	 (0x3637)
#define SVR_PROTO_SYSARG_BUILD_MVP_TEAM      (0xC072)
#define SVR_PROTO_SYSARG_DROP_MVP_TEAM       (0xC073)
#define SVR_PROTO_GET_MVP_TEAM_RANKING       (0xC074)
#define SVR_PROTO_CHANGE_MVP_TEAM_MEMBER_CNT       (0xC075)
#define SVR_PROTO_SYSARG_MVP_GET_TEAMID      (0xC076)
#define SVR_PROTO_SYSARG_SET_MVP_BADGE		     (0xC077)
#define SVR_PROTO_SYSARG_GET_TWO_TEAM_MEDAL_CNT      (0xC078)
#define SVR_PROTO_SYSARG_GET_MVP_TEAM_INFO	 (0xC079)
//piglet rush activity
#define SVR_PROTO_CHOICE_WHICH_PIGLET_CHAMPOIN	 (0x3644)
#define SVR_PROTO_QUERY_WHICH_PIGLET_CHAMPOIN    (0x3645)
#define SVR_PROTO_GET_PIGLET_CHAMPOIN_AWARD    (0x3646)

#define SVR_PROTO_SET_MISS_NOTE    (0x3652)
#define SVR_PROTO_GET_ENERGY_STONE_ROUND   (0x3653)
#define SVR_PROTO_USER_SHAKE_DICE          (0x3654)
#define SVR_PROTO_USER_GET_SHAKE_DICE_LEFT_TIME           (0x3655)
#define SVR_PROTO_CHECK_EXPEDITION_LOCK     (0x3656)
#define SVR_PROTO_SET_CHAPTER_STATE         (0x3657)
#define SVR_PROTO_GET_CHAPTER_STATE         (0x3658)
#define SVR_PROTO_GET_MAKE_SHIP				(0x3659)
#define SVR_PROTO_USER_GET_USER_OCEAN_INFO   (0x365A)
#define SVR_PROTO_USER_PUT_OCEAN_ANIMAL_IN_OCEAN   (0x365C)
#define SVR_PROTO_USER_FEED_OCEAN_ANIMAL   (0x365B)
#define SVR_PROTO_USER_USE_OCEAN_TOOL       (0x365E)
#define SVR_PROTO_USER_EXPAND_OCEAN_CAPACITY    (0x365F)
#define SVR_PROTO_USER_GET_OCEAN_ITEMS    (0x3660)
#define SVR_PROTO_USER_DIY_SELF_OCEAN    (0x365D)
#define SVR_PROTO_USER_GET_OFFLINE_SHELLS    (0x3661)
#define SVR_PROTO_OCENA_CLEAR_DROP_SHELLS_TIME   (0x3662)
#define SVR_PROTO_OCENA_GET_ONLINE_DROP_SHELLS   (0x3663)
#define SVR_PROTO_SALE_OCEAN_FISH           (0x3664)
#define SVR_PROTO_ADD_OCEAN_COIN            (0x3665)
#define SVR_PROTO_BUY_OCEAN_THINGS            (0x3666)
#define SVR_PROTO_GET_OCEAN_ADVENTURE           (0x3668)
#define SVR_PROTO_SET_OCEAN_ADVENTURE           (0x3667)



#define SVR_PROTO_GUESS_SSCLOTH                (0x3670)
#define SVR_PROTO_CHECK_PRIOR_DICE             (0x3671)
#define SVR_PROTO_GET_FREE_VIP_PLAYER          (0xC07C)
#define SVR_PROTO_MERMAN_KINGDOM_EXPEDITION    (0x3672)
#define SVR_PROTO_USER_MIDDLE_YEAR_CHEAP_SEAL  (0x3673)
#define SVR_PROTO_USER_JOIN_COSPLAY_RACE        (0x3674)
#define SVR_PROTO_SET_PRAY_ACITIVITY            (0x3676)
#define SVR_PROTO_GET_PRAY_ACITIVITY            (0x3675)
#define SVR_PROTO_MOLE_GET_SELF_GAMES           (0x3677)
#define SVR_PROTO_GET_OCEAN_HANDBOOK            (0x3669)
#define SVR_PROTO_GET_OCEAN_FRIEND_LEVEL        (0xC170)
#define SVR_PROTO_MOLE_ENTER_GAME_HALL          (0xC171)
#define SVR_PROTO_MOLE_CHANGE_GAME_SCORE         (0xC172)
#define SVR_PROTO_MOLE_CHANGE_USER_GAME          (0x3678)
#define SVR_PROTO_SCROLL_MAP_STAT                (0x367A)
#define SVR_PROTO_SCROLL_FRAGMENT                (0x367B)
#define SVR_PROTO_OCEAN_SYNCHRO_EXP              (0xC173)
#define SVR_PROTO_GET_GAME_EXP_RANK              (0xC174)
#define SVR_PROTO_FINISH_KINGDOM_EXPEDITION      (0x367C)


#define SVR_PROTO_SYSARG_USER_WATER	 (0xC07A)
#define SVR_PROTO_SYSARG_GET_WATER_TIME	 (0xC07B)
#define SVR_PROTO_SYSARG_SET_COS_USER_INFO	 (0xC07D)
#define SVR_PROTO_SYSARG_GET_COS_RANK_INFO	 (0xC07E)
#define SVR_PROTO_SYSARG_GET_COS_RANK_FLAG	 (0xC07F)




#define MONITOR_PROTO_REPORT_ERR					0xF000
#define ADD_ITEM_MASK								0x01
#define USED_ITEM_MASK								0x02

struct user_itm_use_buf {
	uint32_t	id;
	uint8_t		mask;
	item_t		*prop;
}__attribute__((packed));

enum AttrChgReason {
	ATTR_CHG_roll_back		= 4,	// rollback
	ATTR_CHG_play_game		= 1001,	// play game
	ATTR_CHG_buy_pet		= 1002,	// buy pet
	ATTR_CHG_att_party		= 1003,	// attend party
	ATTR_CHG_task_fin		= 1004,	// finished a task
	ATTR_CHG_ask_for		= 1005,	// ask for items
	ATTR_CHG_chk_attr		= 1006,	// check attr only
	ATTR_CHG_collect_ritm	= 1007,	// collect random item
	ATTR_CHG_send_postcard	= 1008,	// send postcard
	ATTR_CHG_trust_pet		= 1009,	// trust pet
	ATTR_CHG_add_wish		= 1010,	// add wish
	ATTR_CHG_fetch_wish		= 1011,	// fetch an unrealized wish
	ATTR_CHG_pet_task		= 1012,	// pick up a pet task
};

extern int udp_dbserver_fd;
extern struct sockaddr_in udp_dbserver_addr;

extern int chatlog_fd;
extern struct sockaddr_in chatlog_addr;

extern int monitor_server_fd;
extern struct sockaddr_in monitor_server_addr;

extern int udp_submit_fd;
extern struct sockaddr_in udp_submit_addr;


extern uint32_t db_timeout_flag;

//extern int udp_third_soft_fd;
//extern struct sockaddr_in udp_third_soft_addr;

extern int chat_monitor_fd;
extern struct sockaddr_in chat_monitor_addr;



int send_request_to_db(int, sprite_t*, int, const void*, uint32_t);
int send_request_to_udp_dbserver(int cmd, sprite_t* p, int body_len, const void* body_buf, uint32_t id);
//int send_request_to_anti_third_soft_server(int body_len, const void* body_buf);
int send_request_to_chatlog_server(int cmd, sprite_t* p, int body_len, const void* body_buf, uint32_t id);
int send_request_to_monitor_dbserver(int cmd, sprite_t* p, int body_len, const void* body_buf, uint32_t id);
int send_request_to_chat_monitor_server(int cmd, sprite_t* p, int body_len, const void* body_buf, uint32_t id);


#define db_add_change_log(p_, len, buf, id) \
		send_request_to_chatlog_server(SVR_PROTO_ADD_CHANGE_LOG, 0, len, buf, (id))
#define db_chk_uid(p_, uid_) \
		send_request_to_db(SVR_PROTO_CHK_UID, (p_), 0, 0, (uid_))
#define db_get_sprite_with_mail(p_) \
		send_request_to_db(SVR_PROTO_GET_MAIL, (p_), 0, NULL, (p_)->id)
#define db_get_sprite(p, id) \
		send_request_to_db(SVR_PROTO_GET_SPRITE, p, 0, NULL, id)
#define db_set_color(p) \
		send_request_to_db(SVR_PROTO_SET_COLOR, p, 4, (void*)&p->color, p->id)
#define db_set_stamp_ip(p, buf, uid_) \
		send_request_to_db(SVR_PROTO_SET_STAMP_IP, p, 8, buf, uid_)
#define db_set_user_nick(p_, nick_) \
		send_request_to_db(SVR_PROTO_SET_USER_NICK, (p_), USER_NICK_LEN, (nick_), (p_)->id)
#define db_forbid_user_24(p_, forbid) \
		send_request_to_db(SVR_PROTO_FORBID_USER_24, 0, 4, (forbid), (p_)->id)

static inline int
db_set_user_flag(sprite_t* p, uint32_t flag, userid_t uid)
{
	return send_request_to_db(SVR_PROTO_SET_USER_FLAG, p, 4, &flag, uid);
}
#define db_add_friend(p_, adder_, addee_) \
		send_request_to_db(SVR_PROTO_ADD_FRIEND, (p_), 4, &(addee_), (adder_))
#define db_del_friend(p, id) \
		send_request_to_db(SVR_PROTO_DEL_FRIEND, p, 4, &id, p->id)
#define db_add_bklist(p, who) \
		send_request_to_db(SVR_PROTO_ADD_BKLIST, p, 4, &who, p->id)
#define db_del_bklist(p, id) \
		send_request_to_db(SVR_PROTO_DEL_BKLIST, p, 4, &id, p->id)
#define db_get_bklist(p) \
		send_request_to_db(SVR_PROTO_GET_BKLIST, p, 0, NULL, p->id)
#define db_add_home_i(p, hi) \
		send_request_to_db(SVR_PROTO_ADD_HOME_I, p, sizeof(*hi), hi, p->id)
#define db_set_home_i(p, b, l) \
		send_request_to_db(SVR_PROTO_SET_HOME_I, p, l, b, p->id)
#define db_reset_home_i(p, b, l) \
		send_request_to_db(SVR_PROTO_RESET_HOME_I, p, l, b, p->id)

#define db_set_home_itm2(p_, uid_, buf_, len_) \
		send_request_to_db(SVR_PROTO_SET_HOME_ITM2, (p_), (len_), (buf_), (uid_))
#define db_del_home_i(p, id) \
		send_request_to_db(SVR_PROTO_DEL_HOME_I, p, 4, &id, p->id)
#define db_get_home_i(p, buf_, id) \
		send_request_to_db(SVR_PROTO_GET_HOME_I, p, 4, buf_, id)
#define db_send_mail(p, id, buf, len) \
		send_request_to_db(SVR_PROTO_ADD_MAIL, p, len, buf, id)
#define db_post_msg(p, msg, len) \
		send_request_to_udp_submit_server(SVR_PROTO_POST_MSG, p, len, msg, p->id)
#define db_post_msg_tw(p, msg, len) \
		send_request_to_udp_dbserver(SVR_PROTO_POST_MSG, p, len, msg, p->id)


// For VIP
#define db_chk_vip_info(p_) \
		send_request_to_db(SVR_PROTO_CHK_VIP_INFO, (p_), 0, 0, (p_)->id)

// type: 0 used for trusted pet cnt, 1 used for on-task pet cnt
//         Mimic Show: 1001 for times of attending, 1002 for times of successful try - not used any more
//         100001 - 100040 for poll
#define db_chk_cnt(p_, type_) \
		send_request_to_db(SVR_PROTO_GET_COUNT, (p_), 4, &(type_), (p_)->id)

static inline void
db_set_cnt(const sprite_t* p, uint32_t type, int increment)
{
typedef struct SetCount {
	uint32_t	type;
	int32_t		increment;
} __attribute__((packed)) set_cnt_t;

	set_cnt_t scnt;
	scnt.type = type;
	scnt.increment = increment;
	send_request_to_db(SVR_PROTO_SET_COUNT, 0, sizeof scnt, &scnt, 0);
}

typedef struct TypeRange {
	uint32_t start;
	uint32_t end;
} __attribute__((packed)) type_range_t;

static inline void
db_get_cnt_list(sprite_t* p, uint32_t start, uint32_t end)
{

	type_range_t tyrange;
	tyrange.start = start;
	tyrange.end = end;
	*(uint32_t*)p->session = start;
	*(uint32_t*)(p->session + 4) = end;
	send_request_to_db(SVR_PROTO_GET_CNT_LIST, p, sizeof tyrange, &tyrange, p->id);
}
static inline void
db_login_get_cnt_list(sprite_t* p, uint32_t start, uint32_t end)
{
	type_range_t	tyrange;
	tyrange.start	= start;
	tyrange.end		= end;
	send_request_to_db(SVR_PROTO_GET_DAY_LIMIT_LIST, p, sizeof tyrange, &tyrange, p->id);
}

static inline int db_set_task(sprite_t* p, uint32_t taskid, uint32_t status)
{
	uint32_t buf[2];
	buf[0] = taskid;
	buf[1] = status;
	return send_request_to_db(SVR_PROTO_SET_TASK, p, 8, buf, p->id);
}

// Temporarily Use Only
#define db_submit_personal_info(p_, buf_) \
		send_request_to_db(SVR_PROTO_SUBMIT_PERSONAL_INFO, (p_), 8, (buf_), (p_)->id)
#define db_chk_if_info_submitted(p_) \
		send_request_to_db(SVR_PROTO_CHK_IF_INFO_SUBMITTED, (p_), 0, 0, (p_)->id)

int db_buy_items(sprite_t* p, const item_t* itm, int count, const item_kind_t* itmkind, int free, int ret_needed);
int db_chg_home_itm(sprite_t* p, userid_t uid, uint32_t itmid, uint32_t cnt, uint32_t chg_flag);
int db_get_items(sprite_t *p, uint32_t type, uint8_t used, uint32_t id, uint8_t kind_flag);
int db_items_op(sprite_t *p);
int db_single_item_op(sprite_t *p, uint32_t uid, uint32_t itmid, int count, int flag);
int db_single_item_op_max_limit(sprite_t *p, uint32_t uid, uint32_t itmid, int count);

int db_exchange_items(sprite_t* p, const exchange_item_t* exitm);
int db_exchg_collected_items(sprite_t* p, const exchange_item_t* exitm, uint32_t item_num);
int db_attr_op(sprite_t* p, int yxb, int exp, int strong, int iq, int lovely, uint32_t reason, uint32_t detailed_reason);
int pkg_item_kind(sprite_t *p, uint8_t* buf, uint32_t itmid, int* indx);
int send_request_to_udp_submit_server(int cmd, sprite_t* p, int body_len, const void* body_buf, uint32_t id);
int exchg_item_callback(sprite_t* p, uint32_t id, char* buf, int len);
int worker_handle_net(int fd, void* buf, int len, sprite_t** u);
void broad_cast_when_fini_task(sprite_t *p, int completed);
int db_buy_items_by_xiaomee(sprite_t* p, const item_t* itm, int count, const item_kind_t* kind, int xiaomee, int ret_needed);
int db_buy_items_by_ocean_shells(sprite_t* p, const item_t* itm, int count, const item_kind_t* kind, int free, int ret_needed);
int db_exchange_single_item_op(sprite_t *p, uint32_t flag, uint32_t itmid, int count, int is_return);
int db_delete_single_item_op(sprite_t *p, uint32_t flag, uint32_t itmid, int count, int is_return);
int db_add_single_item_op(uint32_t userid, uint32_t flag, uint32_t itmid, int count);


static inline int
db_jail_user (sprite_t *p, uint32_t userid, int reason, int count)
{
	char buf[8];

	*(uint32_t *)buf = userid;
	*(int *)(buf + 4) = reason;
	*(uint32_t *)(buf+8) = count;
	
	DEBUG_LOG("JAIL USER\t[==== %u %u %u %u ====]", p->id, userid, reason, count);
	return send_request_to_udp_dbserver(SVR_PROTO_JAIL_USER, p, 12, buf, p->id);
}

static inline int
do_db_attr_op(sprite_t* p, uint32_t chgee, int yxb, int exp, int strong, int iq, int lovely, uint32_t reason, uint32_t detailed_reason)
{
	char buf[28];
	int i = 0;

	PKG_H_UINT32(buf, exp, i);
	PKG_H_UINT32(buf, strong, i);
	PKG_H_UINT32(buf, iq, i);
	PKG_H_UINT32(buf, lovely, i);
	PKG_H_UINT32(buf, yxb, i);
	PKG_H_UINT32(buf, reason, i);
	PKG_H_UINT32(buf, detailed_reason, i);

	return send_request_to_db(SVR_PROTO_CHARGE, p, sizeof buf, buf, chgee);
}

static inline int
db_change_xiaome(sprite_t* p, int yxb, uint32_t reason, uint32_t detailed_reason, uint32_t uid)
{
	int buf[3];

	buf[0] = yxb;
	buf[1] = reason;
	buf[2] = detailed_reason;

	return send_request_to_db(SVR_PROTO_CHANGE_XIAOMEE, p, sizeof buf, buf, uid);
}

static inline int
db_change_xiaome_not_limit(sprite_t* p, int addmoney, uint32_t uid)
{
	int buf[1];
	buf[0] = addmoney;
	return send_request_to_db(SVR_PROTO_ADD_MONEY_NOT_LIMIT, p, sizeof buf, buf, uid);
}

static inline void
send_exchg_itm_rsp(sprite_t* p, int completed)
{
	send_to_self(p, p->session + 29, p->sess_len, completed);
	//uint32_t* tp = (uint32_t*)(p->session + 46);
	//DEBUG_LOG("SEED:%X %X %X %X", *tp, *(tp+1), *(tp+2), *(tp+3));
	//p->sess_len = 0;
}
extern int proxysvr_fd;

static inline void
send_login_exit_info(uint32_t uid, int login_flag, uint32_t online_id, uint32_t login_time)
{
	uint32_t buff_tmp[3];

	buff_tmp[0] = login_flag;
	buff_tmp[1] = online_id;
	buff_tmp[2] = login_time;

	send_request_to_chatlog_server(SVR_PROTO_ADD_LOGIN_EXIT_INFO, 0, sizeof buff_tmp, buff_tmp, uid);
}

static inline int send_err_to_monitor(int cmdid, userid_t uid, int type)
{
	typedef struct packet_struct{
			uint32_t notify_category;	//项目类型;mole:1 ,seer:2
			uint32_t notify_id;			// 服务类型:db:1 ,swtich:2. login:3, online:4, 5 dbproxy
			uint32_t uid;				//用户ID
			uint32_t common_id;			//cmdid(操作的命令号)
	}__attribute__((packed))packet_struct_t;

	if (config_cache.bc_elem->online_id % 30 != 1)
		return 0;

	packet_struct_t lpst;
	lpst.notify_category	= 1;
	lpst.notify_id			= type;
	lpst.uid				= uid;
	lpst.common_id			= cmdid;
	return send_request_to_monitor_dbserver(MONITOR_PROTO_REPORT_ERR, 0, 16, &lpst, 0);
}

int change_vip_level(sprite_t* p, uint32_t change_lvl);
#endif // ONLINE_DBPROXY_H_
